fix repository url
eggjs/vscode-eggjs pull request #4
Opened 2018-03-27 14:39 UTC by bestlong

2018-03-27 14:41 UTC, atian25 requested changes
not, that's correct url

2018-03-27 14:42 UTC, atian25 commented
thanks all the same

2018-03-27 14:54 UTC, bestlong commented
在插件功能畫面有儲存庫的連結，點擊會進入 404 畫面。
<img width="642" alt="2018-03-27 22 46 35" src="https://user-images.githubusercontent.com/4023909/37975360-b647c938-3211-11e8-894a-974f382a3082.png">

2018-03-28 00:19 UTC, atian25 approved these changes

2018-03-28 00:20 UTC, atian25 commented
make sense

2018-03-28 00:20 UTC, merged